# Generated by Django 3.1.3 on 2021-01-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210112_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('comment', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pres',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='patients',
            name='sym',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='dob',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
