# Generated by Django 3.1.3 on 2021-01-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210114_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='comm',
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pres',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='patients',
            name='sym',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='dob',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
