# Generated by Django 3.1.3 on 2021-01-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210114_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pres',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='patients',
            name='sym',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
