# Generated by Django 3.1.3 on 2021-01-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210114_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
